name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 161.35.53.17
          username: root
          key: ${{ secrets.DEPLOY_KEY }}
          script: /var/www/latvian-arbitrage/client/deploy.sh
